package ph.edu.up.antech.util;

public enum NetsuiteChannel {

    DISPENSING_DISTRIBUTOR, BBJ, DIRECT_ACCTS, LAZADA,
    TO_MARKET_ZPC, TO_MARKET_DISPENSING_DISTRIBUTOR, TO_MARKET_BBJ, TO_MARKET_OTHERS

}
