package ph.edu.up.antech.controller.view.demand;

public enum NetsuiteChannel {

    IN_MARKET_DISPENSING_DISTRIBUTOR, IN_MARKET_BBJ, IN_MARKET_DIRECT_ACCTS, IN_MARKET_LAZADA,
    TO_MARKET_ZPC, TO_MARKET_DISPENSING_DISTRIBUTOR, TO_MARKET_BBJ, TO_MARKET_OTHERS

}
